config/routes.rb
Inoride::Application.routes.draw do
  root :to => 'static_pages#home'
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :rides
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  
  

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/find', to: 'static_pages#find_rides', as: 'find'
  match '/rides/users/auth/facebook/callback', to: 'rides#create'
  
  
  #match '/signup', to: 'users#new'
  #match '/signin',  to: 'sessions#new'
  #match '/signout', to: 'sessions#destroy', via: :delete
  
  #match '/users/auth/facebook/callback', to: 'static_pages#home'
  #match 'signout', to: 'sessions#destroy', as: 'signout'
  #match '/auth/failure', to: redirect('/')
  match '/search', to: 'search#search_rides', as: 'search'
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides, dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,
		  :first_name, :last_name, :usr_img, :birthday, :gender, :education,
		  :provider, :uid

  validates_uniqueness_of :email

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.extra.raw_info.name,
			   provider:auth.provider,
			   uid:auth.uid,
			   email:auth.info.email,
			   first_name:auth.info.first_name,
			   last_name:auth.info.last_name,
			   usr_img:auth.info.image,
			   gender:auth.extra.raw_info.gender,
			   password:Devise.friendly_token[0,20]
			   )
      user.save!
    end
    user
  end
  
  def confirm!
    welcome_message
    super
  end
  
  def full_name
    first_name + " " + last_name
  end
  
  private

  def welcome_message
    UserMailer.registration_email(@user).deliver
  end



  #def self.from_omniauth(auth)
  #  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
  #    user.provider = auth.provider
  #    user.uid = auth.uid
  #    user.usr_img= auth.info.image
  #    user.name = auth.info.name
  #    user.password = 'foobar'
  #    user.password_confirmation = 'foobar'
  #    user.first_name = auth.info.first_name
  #    user.last_name = auth.info.last_name
  #    #user.birthday = auth.extra.raw_info.birthday.to_s
  #    #user.gender = auth.extra.raw_info.gender
  #    #user.education= auth.extra.raw_info.education[1].school.name
  #    user.email = auth.info.email
  #    user.oauth_token = auth.credentials.token
  #    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #    user.save!
  #  end
  #end
    

  def self.image
    if usr_img.present?
      usr_img
    else
      usr_img = "/assets/user_placeholder.png"
    end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  #before_filter :correct_user,   only: [:edit, :update]
  #before_filter :admin_user,     only: [:edit, :update, :destroy]
  layout :choose_layout
  
  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page],limit: 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @rides = @user.rides.paginate(page: params[:page])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.registration_email(@user).deliver
      respond_to do |format|
	sign_in @user
	format.html do
	  redirect_back_or @user
	  flash[:success] = "Hey #{current_user.first_name}, welcome to inaride"
	  end
	format.js 
      end
    else
      respond_to do |format|  
        format.html { render 'new' }
        flash.now[:error] = "Failed to create account"
      end
    end
  end
  
  
  

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    #session[:user_id] = nil
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
       
    def choose_layout  
      (request.xhr?) ? 'signup' : 'application'
    end
    
  private

    def correct_user
      @ride = current_user.rides.find_by_id(params[:id])
      flash[:notice] = "Sorry! you do not have permission to do that"
      redirect_to root_url if @ride.nil?
    end
    
    def admin_user
      flash[:notice] = "Only Admins have such powers"
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  # Display placeholder for user profile image if unavailable

  
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
  def profile_image_for(user)
    if user.usr_img.present?
      user.usr_img
    else
      user.usr_img = "/assets/user_placeholder.png"
    end
  end
  
  def full_name
    user.first_name + " " + user.last_name
  end
  
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<fieldset>
<%= f.input :first_name, label: false, placeholder: 'First Name' %>
<%= f.input :last_name, label: false, placeholder: 'Last Name' %>
</fieldset>
<fieldset>
<%= f.input :email, label: false, placeholder: 'Email' %>
</fieldset>
<fieldset>
<%= f.input :password, label: false, placeholder: 'Pick a password' %>
<%= f.input :password_confirmation, label: false, placeholder: 'Confirm Password' %>
</fieldset>

app/views/users/_form.html.erb
<%= simple_form_for(@user, :html => {:class => 'form-inline',remote: true }) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
    
    <%= f.input :first_name, label: false, placeholder: 'First Name' %>
    <%= f.input :last_name, label: false, placeholder: 'Last Name' %>
    <%= f.input :email, label: false, placeholder: 'Email' %>
    <%= f.input :password, label: false, placeholder: 'Pick a password' %>
    <%= f.input :password_confirmation, label: false, placeholder: 'Confirm Password' %>
  <div class="actions">
  <%= f.submit 'Sign up',  class: "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td>
    <div class="driver-info">
      <%= image_tag profile_image_for(user), class: 'profile_img_small' %>
    </div>

    <%= link_to user.first_name, user %><br>
    <% if current_user.admin? || current_user?(user) %>
	<%= link_to 'Edit', edit_user_path(user) %>
	| <%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %>
    <% end %>
    <strong><% if user.admin? %><span class="red">Admin</span><% end %></strong>
  </td>
  <td>
    <span class="rides"><%= user.rides.count %></span>
    <small class="muted">Rides</small>
  </td>
</tr>

app/views/users/_user_rides.html.erb
<table class="table">
<% @user.rides.each do |ride| %>
<tr>
  <td>
    <%= link_to "#{ride.origin} ---> #{ride.destination}", ride %>
    <p class="muted"><%= ride.date.strftime(" %A, %b %d, %Y") %></p>
  </td>
  <td>
    <div class="span price">
      <%= number_to_currency(ride.price, precision: 0) %>
    </div>
  </td>
  
  <% if current_user?(ride.user) && current_user.admin? %>
  <td>
    <%= link_to 'Edit', edit_ride_path(ride) %></li>
    | <%= link_to 'Destroy', ride, confirm: 'Are you sure?', method: :delete %>
  </td>
</tr>
<% end %>
</table>
<% end %>

app/views/users/create.js.erb
$('.modal').modal('hide');
$("ul#user_links").replaceWith("<%= escape_javascript(render "layouts/signedin_user_links") %>");
$("a#login").replaceWith("<input class='btn btn-large btn-success' type='submit' value='Post Ride' name='commit'>");

app/views/users/edit.html.erb
<% provide(:title, 'Edit Proflie') %>
<div id="main" class="container">
  <div class="row-fluid">
    <div class="embos">
	<h1>Edit Profile</h1><hr>
	<%= simple_form_for(@user,:html => {:class => 'form-horizontal' }) do |f| %>
	<%= render 'fields', f: f %>
  
	<div class="controls">
	<%= f.submit "Save Changes", class: "btn btn-large btn-success" %>
	</div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users')%>
<div id="main" class="container">
  <div class="row-fluid">
    <div class="embos">
      <h1>All users</h1><hr>
      <%= will_paginate %>
	<table class="table table-bordered">
	  <%= render @users %>
	</table>
      <%= will_paginate %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div id="main" class="container">
  <div class="row-fluid">
    <section id="signup" class="embos span6 offset3">
	<h1>Sign up</h1>
	<div class="row-fluid">
	    <%# link_to image_tag('fb-logo.png'), "/auth/facebook", class: "sign_in signup span6 btn offset3" %>
	</div>
	
	<div id="signup-form"><hr>
	  <%= simple_form_for(@user,:html => {:class => 'form-horizontal' }) do |f| %>
	  <%= render 'fields', f: f %>
	    <div class="controls">
	    <%= f.submit "Sign up", class: "btn btn-large btn-primary" %>
	    </div>
	    <hr>
	<div class="span5 embos offset3">
	  <%= link_to image_tag('fb-logo.png'), "/auth/facebook", class: "sign_in" %>
	  <%= link_to 'Sign up', "/auth/facebook", class: "btn" %>
	</div>
	  <% end %>
	</div>
    </section>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,"#{@user.first_name}'s profile")%>
<div id="main" class="container">
  <div class="row-fluid">
    <div class="embos">
    <section id="user" class="span4">
      <div class="span">
	<div class="driver-info"><%= image_tag(profile_image_for(@user), options = {:class =>"profile_img_small"})  %></div>
	<div class="offset2">
	  <h1><%= @user.first_name %></h1>
	  <h2><%= @user.last_name %><% if @user.admin %> | <span class="red">Admin</span><% end %></h2>
	</div>
	<hr>
	<% if current_user && current_user.admin? || current_user == @user %>
	  <%= link_to 'Edit Profile', edit_user_path, :class => 'btn btn-mini' %>
	<% end %>
      </div>
      

      <div class="info">
	<% if current_user?(@user) %>
	  <%# link_to 'Edit Profile', edit_user_path, :class => 'btn btn-mini' %>
	<% end %>
      </div>
      <%= @user.birthday %>
      <%= @user.gender %>
      <%= @user.education %>
    </section>	
  
    <section id="rides" class="span8">
      <% if @user.rides.any? %>
	<h3>Rides(<%= @user.rides.count %>)</h3>
	<table class="table">
	<%= render @rides %>
	</table>
      <% else %>
      <%= link_to 'Add Ride', new_ride_path, class: "btn btn-success" if current_user?(@user) %>
      <% end %>
    </section>
    </div>
  </div>
</div>