config/routes.rb
Inoride::Application.routes.draw do
  root :to => 'static_pages#home'
  
  #devise_for :users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  resources :rides
  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  
  
  

  match '/help', to: 'static_pages#help'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/find', to: 'static_pages#find_rides', as: 'find'
  match '/rides/users/auth/facebook/callback', to: 'rides#create'
  
  
  #match '/signup', to: 'users#new'
  #match '/signin',  to: 'sessions#new'
  #match '/signout', to: 'sessions#destroy', via: :delete
  
  #match '/users/auth/facebook/callback', to: 'static_pages#home'
  #match 'signout', to: 'sessions#destroy', as: 'signout'
  #match '/auth/failure', to: redirect('/')
  match '/search', to: 'search#search_rides', as: 'search'
  
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/layouts/_footer.html.erb
<footer class="row-fluid">
<div class="container">
    <small>
    <a href="http://railstutorial.org/"><%=link_to image_tag('footer_logo.png', alt: "inoride"), root_path%>
    <p>&copy; 2012 <a href="https://twitter.com/narokir">@narokir</a></p>
  </small>
  <nav>
    <ul>
      <li><%# link_to "Home", root_path %></li>
      <li><%# link_to "About", about_path %></li>
      <li><%= link_to "Contact", 'mailto: narokir@gmail.com' %></li>
      <li><%# link_to "Help", help_path %></li>
  </nav>
  <%= yield :scripts %>
</div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
	  <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
	 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	 <span class="icon-bar"></span>
	 <span class="icon-bar"></span>
	 <span class="icon-bar"></span>
	 </a>
	<span id="brand"><%= link_to image_tag('logo_bug_white.png',class: "logo"), root_path %></span>


	<%= render 'layouts/usernav' %>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_main_search_form.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&v=3.4&libraries=places" type="text/javascript"></script>


  <%= form_tag search_path, :method => 'get', id: "search-box",class: "form-vertical" do %>
  <p><strong>Fidn a ride:</strong></p>
    <%= text_field_tag :origin, params[:origin], placeholder:"From:", id:"ride_origin",class: "mainsearch span ride_origin",autocomplete:"off"%>
    <%= text_field_tag :destination, params[:destination],placeholder: 'To:', id:"ride_destination",class: "mainsearch span ride_destination",:autocomplete => "off"%>
    <%= text_field_tag :date, params[:date], placeholder: 'Date:',id: "ride_date",class: "mainsearch date-small", :autocomplete => "off"%>
    <%= submit_tag "Find Rides", :name => nil, class: "btn btn-success find-rides" %>
  <% end %>


<script type="text/javascript" charset="utf-8">
   //Prevent origin and location inputs from submiting form when "Enter" pressed
  $('#ride_origin').keydown(function(event) {
  if (event.which == 13) {
     event.preventDefault();
    }
  });
  $('#ride_destination').keydown(function(event) {
  if (event.which == 13) {
     event.preventDefault();
    }
  });
  
  function initialize() {
    var origin = document.getElementById('ride_origin');
    var destination = document.getElementById('ride_destination');
    var autocomplete = new google.maps.places.Autocomplete(origin);
    var autocomplete = new google.maps.places.Autocomplete(destination);
  }
  google.maps.event.addDomListenerOnce(window, 'load',initialize);
</script>

app/views/layouts/_mast.html.erb
<section id="mast" class="">
  <div id="slide1" class="row-fluid active item">
    <div class="container">
      <div class="span7">
	<h1>Ride Together.</h1>
	<p>Split costs, make friends and enjoy a cleaner world.</p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/_masthead_search.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&libraries=places" type="text/javascript"></script>

<div class="masthead-background">
<div class="masthead">
  <div class="container">
    <div class="search-container">
      <section id="searchbar" class =""> 
	<%= form_tag search_path, :method => 'get',class: "form-inline" do %>
      
	  <%= text_field_tag :origin, params[:origin], placeholder: 'From:',class: "ride_origin mainsearch span4",:autocomplete => "off"%>
	  <%= text_field_tag :destination, params[:destination],placeholder: 'To:',class: "ride_destination mainsearch span4",:autocomplete => "off"%>
	  <%= text_field_tag :date, params[:date], placeholder: 'Date:',id: "ride_date",class: "date-small",class: "mainsearch date-small span2"%>
	  <%= submit_tag "Search", :name => nil, class: "btn btn-large btn-primary" %>
      
	<% end %>
	
      </section>
    </div>
  </div>
</div>
</div>

<script type="text/javascript" charset="utf-8">

function initialize() {
  // Add autocomplete to Origin and Destination
  var start = document.getElementById('origin');
  var end = document.getElementById('destination');
  var origin = new google.maps.places.Autocomplete(start);
  var destination = new google.maps.places.Autocomplete(end);
}
google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/layouts/_search.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&v=3.4&libraries=places" type="text/javascript"></script>

<section id="searchbar" class =""> 
  <%= form_tag search_path, :method => 'get', id: "main-search",class: "form-inline" do %>
    <%= text_field_tag :origin, params[:origin], placeholder:"From:", id:"ride_origin",class: "mainsearch span4 ride_origin",autocomplete:"off"%>
    <%= text_field_tag :destination, params[:destination],placeholder: 'To:', id:"ride_destination",class: "mainsearch span4 ride_destination",:autocomplete => "off"%>
    <%= text_field_tag :date, params[:date], placeholder: 'Date:',id: "ride_date",class: "mainsearch date-small", :autocomplete => "off"%>
  <% end %>
</section>
  
</section>


<script type="text/javascript" charset="utf-8">
  // Prevent origin and location inputs from submiting form when "Enter" pressed
  $('#ride_origin').keydown(function(event) {
  if (event.which == 13) {
     event.preventDefault();
    }
  });
  $('#ride_destination').keydown(function(event) {
  if (event.which == 13) {
     event.preventDefault();
    }
  });
  
  function initialize() {
    var origin = document.getElementById('ride_origin');
    var destination = document.getElementById('ride_destination');
    var autocomplete = new google.maps.places.Autocomplete(origin);
    var autocomplete = new google.maps.places.Autocomplete(destination);
  }
  google.maps.event.addDomListenerOnce(window, 'load',initialize);
</script>

app/views/layouts/_search_form.html.erb
<script src="http://maps.googleapis.com/maps/api/js?sensor=true&v=3.4&libraries=places" type="text/javascript"></script>

<section id="searchbar"> 
  <%= form_tag search_path, :method => 'get', id: "main-search",class: "form-inline embos" do %>
    <%= text_field_tag :origin, params[:origin], placeholder:"From:", id:"ride_origin",class: "mainsearch span4 ride_origin",autocomplete:"off"%>
    <%= text_field_tag :destination, params[:destination],placeholder: 'To:', id:"ride_destination",class: "mainsearch span4 ride_destination",:autocomplete => "off"%>
    <%= text_field_tag :date, params[:date], placeholder: 'Date:',id: "ride_date",class: "mainsearch date-small span2", :autocomplete => "off"%>
    <%= submit_tag "Find Rides", :name => nil, class: "btn btn-success find-rides",id: 's' %>
  <% end %>
</section>

<script type="text/javascript" charset="utf-8">
  // Load google maps autocomplete  
  function initialize() {
    var origin = document.getElementById('ride_origin');
    var destination = document.getElementById('ride_destination');
    var autocomplete = new google.maps.places.Autocomplete(origin);
    var autocomplete = new google.maps.places.Autocomplete(destination);
  }
  google.maps.event.addDomListenerOnce(window, 'load',initialize);
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_signedin_user_links.html.erb
<ul id="signedin_user_links" class="nav">
<li class="usrimg">
  <%=image_tag profile_image_for(current_user), class:"fbimg", alt: current_user.first_name%>
</li>

<li class="dropdown">
  <a data-toggle="dropdown" class="dropdown-toggle" href="#"><%= current_user.first_name %> <b class="caret"></b></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Profile", current_user %></li>
    <li>

    <%= link_to 'Edit Profile', edit_user_registration_path %>
    </li>
    <li class="divider"></li>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
  </ul>
</li>
</ul>

app/views/layouts/_user_links.html.erb
<ul id="user_links" class="nav">
<li class="usrimg">
  <% if @usr_img.present? %>
    <%= image_tag current_user.usr_img, class:"fbimg", alt: current_user.first_name %>
  <% else %>
    <%= image_tag ("profile_ico.png"),class:"fbimg" %>
  <% end %>
</li>
    <li><%= link_to "Sign in", new_user_session_path %></li>
    <li><%= link_to "Sign up", new_user_registration_path %></li> 
</ul>

app/views/layouts/_usernav.html.erb
  <div class="span pull-right">
    <%# link_to "New Ride",new_ride_path, class: " btn btn-warning" %>
  </div>
    
  <nav id="controlls">
    <ul class="nav">
      <li><a href="/find">Find<small>Rides</small></a></li>
      <li><a href="/rides/new">Post<small>New Ride</small></a></li>
    </ul>
  </nav>
<nav id="usernav" class="pull-right nav">
  <% if user_signed_in? %>
    <li><%= render 'layouts/signedin_user_links' %></li>
  <% else %>
    <li><%= render 'layouts/user_links' %></li>
  <% end %>
</nav>
<div class="">
    <div id="messages" class="span nav">
    <% flash.each do |key, value| %>
      <div class="fade in alert alert-<%= key %>"><%= value %>
      <a class="close" data-dismiss="alert" href="#">&times;</a>    
  </div>
    <% end %>
  </div>
</div>


<nav id="admin-links" class="nav">
<% if user_signed_in? %>
  <ul class="nav">
    <li><%# link_to 'All Users', users_path %></li>
    <li><%# link_to 'All Rides', rides_path %></li>
  </ul>
<% end %>
</nav>

app/views/layouts/search_results.html.erb
<div class="row-fluid">
  
<div class="span">
  
  <table class="table table-bordered">
    
  <% if @rides.present? %>
    <div class="alert alert-info"><%= pluralize( @rides.count, 'ride' ) %> <%= rides_found_msg %><b></b></div>
    <%= render 'rides' %>
  <% else %>
    <div class="alert">
    <b><%= notice = "0 rides found."%></b> <%= no_rides_found_msg %>
    </div>
  <% end %>
  </table>
</div>

</div>

app/views/layouts/signin.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Login in</h3>
  
</div>
  <div class="strip ">
    <div id="login-errors"></div>
  </div>
  
<div class="modal-body">
  
  <% if flash[:error].present? %>
  <%= render inline: "<div class='alert alert-error'>#{flash[:error]}</div>" %>
  <% end %>
<div class="row">
  
  <div class="span embos">
    <%= link_to image_tag('fb_login_btn_small.png'), "/auth/facebook", class: "sign_in" %>
  </div>
  <div class="span">
    <%= simple_form_for(:session, url: sessions_path, :html => { id:"signin", remote: true }) do |f| %>
      <%= f.input :email, :placeholder => 'Email', :label => false, :label_html => { :class => 'fancy-label' } %>
      <%= f.input :password, :placeholder => 'Password', :label => false, :label_html => { :class => 'fancy-label' } %>
      <%= f.submit "Log in", id: "login",class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<div class="modal-footer">
 Not registered yet? <%= link_to('Signup', "#modal", html_options = {id: 'modalsignup'}) %>
</div>

app/views/layouts/signup.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Sign up</h3>
  <!--<p>Alaready registered ? <%= link_to('login', "#modal", html_options = {id: 'modal-login'}) %></p>-->
</div>
<div class="modal-body">
  <div class="row-fluid">
    <%= render "form" %>
  </div>
</div>
<div class="modal-footer">
  Already Registered? <%= link_to('Signin', "#signin", :id => 'modal-signin') %>
</div>